version: "3"

services:
  api:
    image: dsolab/passets-api:1.0.1
    container_name: passets-api
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_URL=http://passets-elasticsearch:9200
      - ELASTICSEARCH_INDEX=logstash-passets
    ports:
      - 8081:8080
    networks:
      - passets
    restart: unless-stopped
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.4.1
    container_name: passets-elasticsearch
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./data/logs:/usr/share/elasticsearch/logs
    networks:
      - passets
    restart: unless-stopped

  logstash:
    image: logstash:7.4.1
    container_name: passets-logstash
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_URL=http://passets-elasticsearch:9200
      - ELASTICSEARCH_INDEX=logstash-passets
    ports:
      - 5044:5044/udp
    volumes:
      - ./data/logstash:/usr/share/logstash/data
      - ./data/logs:/usr/share/logstash/logs
      - ./logstash/:/usr/share/logstash/config/
      - ./rules/GeoLite2-City.mmdb:/usr/share/logstash/config/GeoLite2-City.mmdb
    restart: unless-stopped
    depends_on:
      - elasticsearch
    networks:
      passets:
        ipv4_address: 172.20.20.100
    entrypoint: ['/usr/share/logstash/bin/logstash', '-f', '/usr/share/logstash/config/logstash.conf', '--config.reload.automatic']

  filter:
    image: dsolab/passets-filter:1.0.1
    container_name: passets-filter
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOST=passets-elasticsearch:9200
      - ELASTICSEARCH_INDEX=logstash-passets
      - THREADS=20
      - CACHE_SIZE=1024
      - DEBUG=0
    volumes:
      - ./config/plugin.yml:/opt/filter/config/plugin.yml
    networks:
      - passets
    restart: unless-stopped
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.4.1
    container_name: passets-kibana
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_URL=http://passets-elasticsearch:9200
    volumes:
      - ./data/logs:/usr/share/kibana/logs
      - ./data/kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - passets
    restart: unless-stopped

  sensor:
    image: dsolab/passets-sensor:1.0.1
    container_name: passets-sensor
    environment:
      - port=5044
      - tag=sensor
      - interface=ens192
      - ip=172.20.20.100
      - debug=off
      - switch=on
    restart: unless-stopped
    depends_on:
      - logstash
    network_mode: host

networks:
  passets:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.20.0/24
