version: "3"

services:
  api:
    image: dsolab/passets-api:1.0.0
    container_name: passets-api
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_URL=passets-elasticsearch:9200
      - ELASTICSEARCH_INDEX=logstash-passets
      - SECRET=<dsolab-passets-api-secret>
    ports:
      - 8081:8080
    networks:
      - passets
    restart: unless-stopped
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.5.1
    container_name: passets-elasticsearch
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./data/logs:/usr/share/elasticsearch/logs
    networks:
      - passets
    restart: unless-stopped

  logstash:
    image: dsolab/passets-logstash:1.0.0
    container_name: passets-logstash
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_URL=passets-elasticsearch:9200
      - ELASTICSEARCH_INDEX=logstash-passets
      - INNER_IP_LIST=10.0.0.0-10.255.255.255,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,169.254.0.0-169.254.255.255,127.0.0.1-127.0.0.255
    ports:
      - 5044:5044/tcp
    volumes:
      - ./data/logstash:/usr/share/logstash/data
      - ./data/logs:/usr/share/logstash/logs
    restart: unless-stopped
    depends_on:
      - elasticsearch
    networks:
      passets:
        ipv4_address: 172.20.20.100

  filter:
    image: dsolab/passets-filter:1.0.0
    container_name: passets-filter
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_URL=passets-elasticsearch:9200
      - ELASTICSEARCH_INDEX=logstash-passets
      - THREADS=20
      - CACHE_SIZE=256
      - DEBUG=0
    volumes:
      - ./rules/:/opt/filter/rules/
      - ./config/plugin.yml:/opt/filter/config/plugin.yml
    networks:
      - passets
    restart: unless-stopped
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.5.1
    container_name: passets-kibana
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://passets-elasticsearch:9200
      - I18N_LOCALE=zh-CN
    volumes:
      - ./data/logs:/usr/share/kibana/logs
      - ./data/kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - passets
    restart: unless-stopped

  sensor:
    image: dsolab/passets-sensor:1.0.0
    container_name: passets-sensor
    environment:
      - port=5044
      - tag=sensor
      - interface=ens192
      - ip=172.20.20.100
      - debug=off
      - cache=1024
      - timeout=3600
    restart: unless-stopped
    privileged: true
    depends_on:
      - logstash
    network_mode: host

networks:
  passets:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.20.0/24
